name: "tagged release"
on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "macos-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Set Up Go"
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: "Get gox"
        run: |
          go install github.com/mitchellh/gox@v1.0.1

      - name: "Build & Quick Test"
        run: |
          make
          bin/alpine list >/dev/null

      - name: "Make Release Files"
        run: |
          make xcompile
          ls bin/alpine_darwin_arm64 bin/alpine_darwin_amd64 || exit 1           # ensure binaries are built

      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.md
            bin/alpine_darwin_arm64
            bin/alpine_darwin_amd64

      - name: "Update Homebrew Formula"
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.PUBLIC_RW_TOKEN }} # requires token with 'public_repo' scope
          formula: macpine
          livecheck: true
